'use client'
import { Geist, Geist_Mono } from "next/font/google";
import { useState } from "react";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [count, setCount] = useState(0);
  return (
    <div className="border border-red-500 text-[red] mx-10">
        <div>根 home </div>
        <div>
          {children} -- count {count}
          <button onClick={() => setCount(count + 1)}>add count</button>
        </div>
        <div>根 home</div>
        <div>
        </div>
    </div>
  );
}
